# Generated by Django 2.0.3 on 2018-04-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180410_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blogs.Category', verbose_name='categorias'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blogs.Tags', verbose_name='tags'),
        ),
    ]
